version: "3.9"
name: eigen-tech-test
services:
  app:
    image: afx-eigen-test/app
    container_name: afx-eigen-test
    build: ./app
    restart: always
    ports:
      - 4010:4010
    networks:
      connectors:
        ipv4_address: 183.77.86.10
    depends_on:
      - db
  db:
    container_name: pg-tech-test
    image: postgres
    environment:
      POSTGRES_DB: eigen_afx_dev
      POSTGRES_USER: aidil
      POSTGRES_PASSWORD: febrian98
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    restart: always
    ports:
      - 8856:5432
    networks:
      connectors:
        ipv4_address: 183.77.86.5
networks:
  connectors:
    name: afx-crud-network
    driver: bridge
    ipam:
      config:
        - subnet: "183.77.86.0/24"
          gateway: "183.77.86.1"
    attachable: true
